[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 